version: '3.7'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     networks:
       - backend
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - wp_data:/var/www/html
     networks:
       - backend
       - proxy
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     deploy:
       labels:
         traefik.port: 80
         traefik.frontend.rule: "Host:wp.34.78.218.131.nip.io,wp.130.211.61.65.nip.io,wp.34.77.99.84.nip.io"
         traefik.docker.network: "proxy"

volumes:
    db_data: {}
    wp_data: {}

networks:
    backend: 
      driver: overlay
    proxy: 
      external: true
